In [ ]:
import numpy as np
import ipdb
from collections import defaultdict
from pprint import pprint

In [142]:
idx_dict=defaultdict(lambda:len(idx_dict))
phi_dict=defaultdict(int)

In [143]:
def update_phi(line,isupdate=True):
    if isupdate:
        for w in line.split():
            phi_dict[idx_dict[w]]+=1

In [144]:
def get_lines_from_file(f_name):
    for line in open(f_name, "r",encoding="utf-8"):
        yield line

In [145]:
for line in get_lines_from_file("../../test/03-train-input.txt"):
    cls, line=line.split("\t")
    update_phi(line)

In [146]:
pprint(idx_dict)
phi_array=np.array(phi_dict.values())
pprint(phi_array)
assert len(idx_dict)==len(phi_dict)

defaultdict(<function <lambda> at 0x1055f41e0>,
            {',': 2,
             'A': 0,
             'Kyoto': 6,
             'Maizuru': 5,
             'Shoken': 7,
             'born': 9,
             'in': 4,
             'located': 3,
             'monk': 8,
             'site': 1})
array(dict_values([1, 1, 3, 1, 2, 1, 2, 1, 1, 1]), dtype=object)


In [147]:
def gen_training_phi(line):
    phi_arrapy_=np.zeros(len(phi_dict))
    for w in line.split():
        phi_array_[idx_dict[w]]+=1
    return phi_array_

In [148]:
for line in get_lines_from_file("../../test/03-train-input.txt"):
    cls, line=line.split("\t")
    print(gen_training_phi(line))

[ 1.  1.  2.  1.  1.  1.  1.  0.  0.  0.]
[ 0.  0.  1.  0.  1.  0.  1.  1.  1.  1.]


In [197]:
def initialize_networks(*num_neurons_network):
    num_neurons_prev=len(idx_dict)
    ws_network=[]
    bs_network=[]
    for num_neurons_current in num_neurons_network:
        ws_layer=[]
        bs_layer=[]
        for n in range(num_neurons_current):
            ws_v=np.random.rand(num_neurons_prev)
            ws_layer.append(ws_v)
            bs_layer.append(1)
        num_neurons_prev=num_neurons_current
        ws_network.append(ws_layer)
        bs_network.append(bs_layer)
    return ws_network,bs_network
        

In [198]:
ws_network,bs_network=initialize_networks(3,2,1)
pprint(ws_network)
pprint(bs_network)

[[array([ 0.23123685,  0.61761262,  0.79039268,  0.26999489,  0.45111697,
        0.05725738,  0.628808  ,  0.36174205,  0.49867506,  0.89518292]),
  array([ 0.87139379,  0.64587763,  0.74341105,  0.26843137,  0.86165433,
        0.56882469,  0.69224547,  0.83599718,  0.51892731,  0.86453517]),
  array([ 0.46889032,  0.04488942,  0.36851191,  0.21869868,  0.77609211,
        0.35035053,  0.05367213,  0.60235781,  0.41899452,  0.48016793])],
 [array([ 0.07445069,  0.32431077,  0.37890312]),
  array([ 0.95631306,  0.06186148,  0.38187984])],
 [array([ 0.41877334,  0.58336451])]]
[[1, 1, 1], [1, 1], [1]]


In [199]:
def forward_nn(ws_network,bs_network,phi_input):
    phi_array_prev=phi_input
    phi_network=[]
    for idx_layer,ws_layer in enumerate(ws_network):
        phi_layer=[]
        for idx_v,ws_v in enumerate(ws_layer):
            phi_layer.append(np.tanh(np.dot(phi_array_prev,ws_v)+bs_network[idx_layer][idx_v]))
        phi_array_prev=phi_layer
        phi_network.append(phi_layer)
    return phi_network

In [201]:
phi_network=forward_nn(ws_network,bs_network,gen_training_phi("Shoken , monk born in Kyoto"))
pprint(phi_network)

[[0.99980814758074166, 0.99996769892313575, 0.99877774399779651],
 [0.94439069527489583, 0.98365548586114948],
 [0.96179432305318702]]


In [151]:
b=np.array([ 0.44718688,  0.02151068,  0.06308948,  0.01271954,  0.27276764,
        0.83212791,  0.4848249 ,  0.03118655,  0.40762504,  0.2842886 ])

In [152]:
np.dot(a,b)

2.1973165100000003