In [78]:
import numpy as np
from pprint import pprint
import pdir

In [72]:
class NN():
    def __init__(self, input_matrix, labels, network_dims):
        """initialize the network. all hidden and output nodes are calculated by tanh(sum(x*w))
            ================input=================
            input_matrix:
                np.matrix, each line (axis 0) represents an input vector
            labels:
                np.array, each item represents a label
            network_dims:
                tuples, the dimensions of the network (not including the input dim)"""
        assert input_matrix.shape[1] == labels.shape[0]

        self.input_matrix = input_matrix
        self.labels = labels
        self.network_neuron_outputs = []
        self.network_grads = []
        self.network_weights = []
        self.network_neuron_values=[]
        for dim,dim_prev in zip(network_dims,(labels.shape[0],*network_dims)):
#             print(dim,dim_prev)
#             input()
            layer_neuron_outputs = np.zeros((dim, 1))
            layer_neuron_values=np.zeros_like(layer_neurons)
            layer_grads = np.zeros_like(layer_neurons)
            layer_weights=np.random.rand(dim_prev,dim)
            
            self.network_neuron_values.append(layer_neuron_values)
            self.network_neurons.append(layer_neurons)
            self.network_grads.append(layer_grads)
            self.network_weights.append(layer_weights)
            
    def ff_one(self, line):
        """feed forward for one time; update the neurons based on weights
            for one neuron: 
                n_val=N_prev * W_current
                n_out=tanh(n_val)
            ================input==============
            line:
                np.array, the input vector
                """
        assert line.shape[0]==self.network_weights[0].shape[0]
        for idx,weights_m in enumerate(self.network_weights):
            if idx==0:
                neurons_prev=line
            else:
                neurons_prev=self.network_neurons[idx-1]
            self.network_neuron_values[idx]=np.matmul(neurons_prev,weights_m)
            self.network_neurons[idx]=np.tanh(self.network_neuron_values[idx])

    def bk_one(self, label):
        """calculate the gradient value at each node
            
            =================input=================
            label:
                np.array of (1, ),the label of the output"""
        assert label.shape[0]==1
        for idx,grads in enumerate(reversed(self.network_grads)):
            if idx==0:
                err_grad=label-self.network_neurons[-1]

In [73]:
nn=NN(a,b,(3,1))

In [74]:
nn.ff_one(np.array([1,2,3,4,5]))
nn.ff_one(np.array([2,3,4,5,6]))

In [80]:
pprint(nn.__dict__,)

{'input_matrix': array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]]),
 'labels': array([1, 2, 3, 4, 5]),
 'network_grads': [array([[ 0.],
       [ 0.],
       [ 0.]]), array([[ 0.]])],
 'network_neuron_values': [array([  4.69870327,  11.30359916,   8.21221944]),
                           array([ 1.21449741])],
 'network_neurons': [array([ 0.99983414,  1.        ,  0.99999985]),
                     array([ 0.8380235])],
 'network_weights': [array([[ 0.20627635,  0.80544132,  0.75248393],
       [ 0.76875593,  0.02722891,  0.2475711 ],
       [ 0.12710566,  0.95264163,  0.31045845],
       [ 0.17432225,  0.63051599,  0.48039315],
       [ 0.09997482,  0.44131389,  0.38678978]]),
                     array([[ 0.20988014],
       [ 0.18208367],
       [ 0.82256853]])]}


In [16]:
a.shape

(6, 5)

In [16]:
c.shape

(4, 3)

In [1]:
t="""P. Noyes and others, "Low Level Exposure to the Flame Retardant BDE-209 Reduces Thyroid Hormone Levels and Disrupts Thyroid Signaling in Fathead Minnows", Environmental Science & Technology, Vol. 47, No. 17 (2013), pp. 10012−10021.
"""

In [4]:
t.decode("utf-8").encode("utf-8")

'P. Noyes and others, "Low Level Exposure to the Flame Retardant BDE-209 Reduces Thyroid Hormone Levels and Disrupts Thyroid Signaling in Fathead Minnows", Environmental Science & Technology, Vol. 47, No. 17 (2013), pp. 10012\xe2\x88\x9210021.\n'