In [226]:
import numpy as np
from pprint import pprint
from time import time
import pdir

In [209]:
def gen_ids(f_names):
    words=[]
    labels=[]
    for line in open(f_names,"r",encoding="utf-8"):
        label,sentence=line.split("\t")
        labels.append(int(label))
        for w in sentence.split():
            words.append(w)
    words=set(words)
    w_ids={}
    
    for w in words:
        w_ids[w]=len(w_ids)
    sentences=[]
    for line in open(f_names,"r",encoding="utf-8"):
        label,sentence=line.split("\t")
        sent=np.zeros(len(w_ids))
        for w in sentence.split():
            sent[w_ids[w]]+=1
        sentences.append(sent)
    return w_ids,sentences,labels

In [249]:
def gen_sent_phi(sentence,w_ids):
    sent=np.zeros(len(w_ids))
    for w in sentence.split():
        if w in w_ids:
            sent[w_ids[w]]+=1
    return sent

In [211]:
w_ids,sentences,labels=gen_ids("../../data/titles-en-train.labeled")

In [212]:
sentences

[array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0

In [213]:
labels

[1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 

In [243]:
class NN():

    def __init__(self, input_list, labels,w_ids, network_dims):
        assert len(input_list) == len(labels)
        
        self.w_ids=w_ids
        
        self.input_list = input_list
        self.labels = labels
        self.network_neuron_outputs = []
        self.network_neuron_nets = []
        self.network_neuron_bias = []

        self.network_neuron_derr_net = []
        self.network_neuron_dnet_weight = []

        self.network_weights = []

        dim_prev = len(input_list[0])
        for i in range(len(network_dims)):
            dim = network_dims[i]
            self.network_weights.append(np.random.rand(dim_prev, dim) / 10)
            self.network_neuron_bias.append(np.random.rand(dim) / 10)
            self.network_neuron_outputs.append(np.zeros((dim)))
            self.network_neuron_nets.append(np.zeros((dim)))
            self.network_neuron_derr_net.append(np.zeros((dim)))
            self.network_neuron_dnet_weight.append(np.zeros((dim)))
            dim_prev = dim

        self.network = (self.network_neuron_outputs, self.network_neuron_nets,
                        self.network_neuron_derr_net,
                        self.network_neuron_dnet_weight)

    def print_network(self):
        for w in self.__dict__:
            if w.startswith("network"):
                print(w)
                pprint(self.__dict__[w])
                print()

    def ff_one(self, input_array):
        self.input_array = input_array
        for idx in range(len(self.network_weights)):
            if idx == 0:
                outputs_prev = input_array
            else:
                outputs_prev = self.network_neuron_outputs[idx - 1]
            self.network_neuron_nets[idx] = np.dot(
                outputs_prev,
                self.network_weights[idx]) + 1 * self.network_neuron_bias[idx]
            self.network_neuron_outputs[idx] = np.tanh(
                self.network_neuron_nets[idx])

    def bk_one(self, label):
        err = label - self.network_neuron_outputs[-1]
        for i in reversed(range(len(self.network_neuron_outputs))):
            out = self.network_neuron_outputs[i]
            net = self.network_neuron_nets[i]
            if i != 0:
                out_prev = self.network_neuron_outputs[i - 1]
            else:
                out_prev = self.input_array
            w = self.network_weights[i]
            if i == len(self.network_neuron_outputs) - 1:
                derr_out = label - self.network_neuron_outputs[-1]
            else:
                derr_out = np.dot(self.network_neuron_derr_net[i + 1],
                                  self.network_weights[i + 1].T)
            dout_net = 1 - out**2
            

            self.network_neuron_derr_net[i] = derr_out * dout_net
            dnet_weight = np.outer(out_prev, self.network_neuron_derr_net[i])

            self.network_neuron_dnet_weight[i] = dnet_weight

    def update_weight(self, lrate=0.01):
        for i in range(len(self.network_weights)):
            self.network_weights[i] += self.network_neuron_dnet_weight[
                i] * lrate
            self.network_neuron_bias[i] += self.network_neuron_derr_net[
                i] * lrate

    def train(self, epoch=10, lrate=0.01):
        for i in range(epoch):
            start=time()
            print("Epoch start:\t{}".format(i+1))
            for input_array, label in zip(self.input_list, self.labels):
                self.ff_one(input_array)
                self.bk_one(label)
                self.update_weight(lrate=lrate)
            print("Epoch ends:\t{}. Spending {:0.2f} seconds.\n".format(i+1,time()-start))
    def predict(self,sent):
        self.ff_one(gen_sent_phi(sent,self.w_ids))
        cls=self.network_neuron_outputs[-1]
        if cls>0:
            return 1
        else:
            return -1
            

In [244]:
nn=NN(sentences,labels,w_ids,(2,1))

In [245]:
nn.train(epoch=10,lrate=0.1)

Epoch start:	1
Epoch ends:	1. Spending 8.30 seconds.

Epoch start:	2
Epoch ends:	2. Spending 8.25 seconds.

Epoch start:	3
Epoch ends:	3. Spending 8.25 seconds.

Epoch start:	4
Epoch ends:	4. Spending 8.26 seconds.

Epoch start:	5
Epoch ends:	5. Spending 8.19 seconds.

Epoch start:	6
Epoch ends:	6. Spending 8.22 seconds.

Epoch start:	7
Epoch ends:	7. Spending 8.70 seconds.

Epoch start:	8
Epoch ends:	8. Spending 8.84 seconds.

Epoch start:	9
Epoch ends:	9. Spending 8.45 seconds.

Epoch start:	10
Epoch ends:	10. Spending 8.34 seconds.



In [250]:
test_file="../../data/titles-en-test.word"
with open("my-answer","w",encoding="utf-8") as f:
    for sent in open(test_file,"r",encoding="utf-8"):
        f.write("{}\t{}\n".format(nn.predict(sent),sent))

131

137

120

166

101

130

74

214

114

224

146

137

87

39

111

155

111

90

229

110

301

52

114

123

84

102

110

185

40

168

121

239

197

293

141

117

109

158

75

211

116

77

74

183

163

85

219

120

228

139

78

121

212

85

86

110

259

154

182

111

201

129

86

122

88

257

99

113

70

104

96

217

251

100

161

86

115

274

131

224

107

121

129

372

163

212

76

110

194

118

98

110

294

171

145

128

169

134

77

178

112

70

164

135

126

125

75

151

80

99

225

181

136

134

94

106

98

124

116

242

147

123

168

121

118

96

95

136

151

183

120

107

138

155

110

155

220

103

127

155

117

183

125

209

87

124

118

127

141

110

145

71

140

211

115

189

226

138

351

161

82

130

214

120

45

271

231

139

160

153

108

195

69

110

213

127

245

350

156

209

78

221

111

111

163

414

185

48

85

253

249

176

134

137

126

47

58

99

55

86

195

163

112

300

262

208

143

135

129

105

146

137

117

115

102

101

165

67

126

147

184

161

405

130

80

127

157

79

111

169

63

92

133

73

60

145

49

97

112

151

354

185

47

87

115

126

125

138

199

172

187

94

121

85

152

146

88

171

165

56

77

163

207

118

171

157

123

154

126

93

174

173

251

370

96

240

142

231

215

92

79

222

72

188

165

83

143

141

182

214

160

145

135

149

105

193

135

114

133

108

113

183

92

174

133

199

136

80

91

331

80

128

163

412

179

74

472

142

178

60

142

126

84

143

207

180

83

77

179

52

58

75

87

43

142

104

83

148

116

113

111

132

48

67

117

179

97

226

102

149

165

174

105

225

187

113

120

230

92

76

176

116

112

99

64

102

387

153

163

266

97

72

143

67

91

135

168

99

94

101

122

25

139

187

221

189

108

95

191

28

281

132

85

111

202

101

235

69

95

139

127

80

154

96

34

128

254

126

88

102

88

167

99

122

155

183

109

155

110

108

124

102

64

154

120

176

167

112

201

112

102

99

85

127

195

302

114

106

166

175

351

71

222

94

210

226

239

89

96

216

101

120

146

131

152

122

118

84

74

173

124

184

82

128

34

185

137

26

113

139

218

107

184

136

115

249

125

126

182

191

142

152

102

147

148

101

74

104

107

64

323

78

169

272

100

98

147

181

102

137

199

150

145

181

239

98

140

122

123

80

108

120

139

75

110

86

84

66

140

135

147

61

91

73

259

267

147

149

118

137

131

89

99

270

58

116

235

130

122

236

89

336

135

97

90

92

131

155

119

105

96

293

119

106

186

93

114

120

12

132

152

74

109

371

224

143

119

141

103

224

128

106

58

155

212

84

139

87

129

137

165

336

302

118

73

12

203

88

136

110

64

88

115

98

179

96

162

97

125

98

234

184

111

177

98

100

87

199

174

71

113

22

109

108

144

290

135

76

124

123

215

225

107

151

138

311

176

308

330

151

157

173

83

17

160

176

294

195

113

77

124

127

289

160

289

133

106

112

207

147

130

75

190

69

97

113

44

72

105

147

270

201

242

130

114

168

129

199

122

94

104

204

167

229

274

145

95

149

78

38

127

108

135

161

96

151

115

204

109

119

98

190

107

139

109

107

88

664

289

98

93

119

100

153

121

138

140

123

68

108

112

123

110

130

144

86

96

87

63

231

98

146

284

159

244

104

127

176

104

161

144

83

144

127

138

95

90

165

117

121

64

61

113

73

162

164

156

168

206

103

121

158

107

159

162

178

312

61

123

106

76

121

152

138

183

111

121

146

165

247

108

250

83

114

85

574

122

95

179

194

85

182

116

176

202

59

147

154

182

94

78

130

118

157

192

123

46

147

28

243

207

117

58

84

97

236

64

122

159

143

224

153

75

119

247

93

90

135

159

439

147

170

195

170

166

28

102

166

223

174

365

149

189

90

70

226

253

74

150

132

120

252

176

308

99

103

144

109

81

246

174

208

205

292

89

102

170

277

71

135

132

235

108

123

111

81

133

107

82

108

108

87

250

109

122

150

138

142

101

132

60

236

88

91

181

216

236

200

167

91

238

147

246

94

172

171

85

106

84

88

180

106

76

73

89

290

160

117

264

242

190

84

253

312

97

61

99

88

125

84

120

335

130

59

85

94

145

113

102

160

7

66

106

114

132

104

100

234

111

80

257

203

107

171

136

128

112

79

116

94

106

90

147

137

126

235

99

111

219

127

132

226

81

118

114

101

125

217

71

126

182

48

55

105

98

61

166

112

130

19

169

136

66

253

165

74

54

75

146

92

111

164

176

109

211

96

275

67

114

151

96

120

116

112

165

76

88

87

156

115

123

84

99

86

90

228

109

66

147

157

148

114

57

110

131

98

86

169

202

101

71

104

206

83

151

159

193

110

228

47

133

155

189

163

166

161

12

121

95

180

386

123

101

172

224

187

189

166

158

196

31

101

129

254

298

237

92

92

116

125

92

80

106

132

277

97

227

133

71

145

153

89

114

90

214

43

109

206

119

148

128

107

98

220

176

105

158

134

144

98

186

103

90

71

102

122

83

121

96

58

120

153

111

83

157

212

140

243

139

107

174

143

199

128

130

108

182

83

326

109

105

109

97

153

79

62

170

114

94

158

74

154

82

371

86

151

95

101

134

127

328

144

234

312

168

166

90

144

204

44

162

132

321

124

102

93

78

168

64

151

55

205

201

66

143

195

523

215

205

64

140

11

76

114

147

104

142

133

161

153

163

291

231

316

63

165

125

162

83

188

59

183

58

95

111

109

99

141

90

218

147

73

106

95

72

164

149

126

145

151

202

147

90

102

100

107

229

85

369

101

89

178

275

101

201

87

163

133

259

143

66

158

294

115

104

103

135

537

119

112

153

222

208

83

99

244

87

338

95

151

111

167

96

144

176

106

108

230

70

64

235

140

118

137

184

147

183

255

100

115

98

141

55

117

121

91

103

191

129

123

129

87

140

101

179

87

112

20

66

181

112

310

187

171

116

91

191

22

216

182

90

76

153

274

281

50

17

106

124

101

250

139

94

126

328

99

87

78

224

52

177

143

162

130

123

123

129

93

208

100

96

201

69

105

136

111

92

68

117

96

154

394

118

194

165

93

115

203

83

277

192

125

138

67

192

127

68

499

62

138

121

166

220

76

191

320

90

165

222

123

216

102

172

147

138

100

255

96

112

90

228

57

65

133

154

120

88

125

118

78

51

47

235

29

60

74

22

49

174

124

139

181

131

15

130

187

447

126

149

210

107

109

69

180

147

156

146

109

99

111

100

110

88

162

96

94

253

85

96

115

121

101

138

103

117

228

114

187

135

88

131

121

293

82

88

132

103

163

202

119

119

242

101

25

90

100

236

114

172

351

145

336

253

134

173

186

189

171

99

153

95

175

127

126

167

155

220

134

60

89

368

135

99

224

184

199

128

171

125

120

97

134

119

128

86

123

100

249

196

154

121

80

80

311

87

191

134

103

86

139

201

199

115

172

121

106

78

156

261

108

119

122

126

87

115

199

113

61

238

132

93

95

138

109

107

120

114

11

108

137

91

228

83

245

97

133

62

117

116

229

103

275

235

170

98

160

85

295

141

95

124

98

275

134

178

152

100

130

92

265

74

231

137

128

341

97

91

112

181

150

198

125

104

187

74

102

101

136

120

77

130

119

85

156

118

68

309

112

128

217

213

126

78

91

58

90

145

87

89

129

88

159

457

187

137

107

157

331

148

98

139

184

187

73

545

132

144

94

96

169

113

116

108

227

182

58

268

110

235

113

95

62

118

272

121

73

87

169

127

122

104

105

53

54

124

105

89

86

77

121

161

122

172

178

111

135

148

72

120

102

45

168

118

117

143

213

175

107

164

246

138

105

71

105

204

92

149

157

81

184

79

96

81

103

89

122

167

203

130

206

175

212

80

131

345

319

265

98

142

287

100

79

109

113

195

85

105

202

159

178

116

92

129

198

134

217

169

131

123

165

135

116

156

71

159

126

216

170

9

101

156

136

148

145

128

96

125

100

68

175

119

125

197

185

102

124

140

106

194

106

121

258

137

175

177

38

136

66

289

157

186

94

82

129

254

325

90

73

140

122

190

133

154

69

85

188

82

143

107

141

95

193

91

151

207

106

138

135

120

154

84

80

75

64

96

72

90

71

152

252

100

104

118

137

155

517

165

7

188

11

104

150

60

48

59

560

115

99

146

305

242

161

148

153

149

100

161

188

117

220

178

137

148

92

297

89

56

232

60

168

10

335

176

152

209

153

75

130

116

277

234

432

96

16

100

94

12

209

87

253

64

93

104

92

190

103

115

111

116

108

137

128

149

120

127

187

81

202

201

113

155

88

102

159

165

228

172

84

177

143

311

130

110

228

235

69

113

96

104

96

149

132

147

159

96

446

126

187

108

81

92

171

90

133

146

146

233

139

78

55

303

141

82

149

295

120

131

99

113

115

70

146

118

98

101

144

141

408

180

144

156

100

107

152

135

127

77

198

203

205

40

191

117

161

464

142

76

130

195

193

244

141

190

118

118

193

185

98

172

241

101

128

198

226

153

240

511

185

143

237

100

110

115

54

102

197

136

95

106

83

17

96

179

141

108

80

193

127

112

134

124

150

131

373

81

236

164

124

83

59

177

229

107

259

74

123

75

214

84

84

117

116

214

281

182

152

119

250

84

255

114

63

109

135

363

223

207

100

97

76

145

255

104

334

113

101

161

144

54

182

163

82

115

196

143

88

119

182

128

123

114

156

234

64

152

142

272

123

108

28

60

101

204

156

147

128

222

121

81

161

113

142

198

51

122

109

130

136

235

92

103

160

200

116

83

136

131

64

151

140

632

137

200

111

137

95

109

198

145

127

161

263

165

114

95

204

106

217

187

118

258

174

117

77

241

70

146

137

141

100

21

79

193

237

225

87

87

80

116

124

108

281

105

174

101

254

120

161

132

221

103

204

102

116

147

128

39

70

99

157

212

143

193

95

130

74

128

179

393

77

77

110

164

118

144

194

168

107

202

212

181

179

74

234

84

82

120

96

116

192

119

102

137

118

77

153

187

155

201

155

120

122

97

149

147

141

43

223

102

253

118

207

164

66

255

95

106

335

102

116

18

162

134

109

107

142

57

121

215

124

99

136

110

81

147

143

119

141

295

170

131

67

133

163

124

91

109

93

190

386

119

173

272

127

59

164

66

162

140

97

105

96

124

184

188

151

184

350

113

159

119

99

197

98

212

111

68

175

88

153

113

42

95

141

215

75

134

131

130

129

129

263

54

130

130

178

166

280

150

145

83

93

168

165

125

137

191

28

117

87

120

131

255

123

279

164

194

96

93

204

181

94

96

196

159

141

175

86

120

127

197

43

118

154

137

122

76

62

144

67

133

91

254

96

91

132

506

119

184

262

106

79

112

45

115

69

138

123

143

94

127

232

231

72

162

96

126

107

174

120

393

95

108

128

281

81

93

41

118

109

118

116

122

177

126

115

164

209

267

88

51

109

119

127

76

99

62

139

98

35

206

176

162

92

115

81

148

101

207

164

225

21

264

143

33

134

81

82

103

225

393

159

101

198

154

172

155

90

269

277

91

171

156

80

76

110

152

164

192

263

85

265

220

121

55

111

117

104

100

95

232

135

110

232

80

53

101

83

127

105

199

101

93

102

44

155

137

124

175

84

78

109

58

126

102

173

251

182

115

94

182

126

110

175

142

115

141

252

165

97

71

135

241

60

108

64

93

248

109

146

101

107

12

116

50

210

113

157

178

120

42

106

155

285

102

20

201

101

92

120

110

260

149

96

141

304

170

80

102

146

164

70

116

163

120

125

199

92

128

146

92

137

174

136

175

319

81

164

124

168

185

106

184

91

158

102

56

35

171

130

54

161

114

62

106

119

103

204

179

80

598

150

136

106

96

77

92

177

134

273

75

240

97

157

403

160

157

237

73

295

297

108

146

134

47

97

153

77

155

131

166

244

75

180

72

108

157

108

116

81

123

171

116

72

130

122

186

90

107

209

122

107

144

112

251

135

72

85

115

347

106

163

179

136

272

68

45

90

123

118

97

186

82

130

14

127

82

235

147

345

57

170

95

104

79

170

199

172

83

111

109

128

136

146

319

106

192

134

148

228

117

60

145

18

201

207

142

79

101

94

57

80

105

159

211

124

146

84

104

189

146

109

175

120

12

114

71

92

65

147

106

356

156

127

112

180

79

137

104

143

105

71

102

125

266

110

121

168

140

215

75

143

45

247

264

119

166

180

316

118

96

246

93

229

230

382

132

58

159

105

100

170

115

96

107

179

65

126

127

99

158

103

215

126

216

105

186

216

173

239

107

155

283

205

128

106

135

63

198

104

237

177

132

76

105

91

100

120

90

208

181

158

121

223

126

170

171

82

141

292

92

239

253

141

145

123

108

417

102

108

192

119

156