In [2]:
import numpy as np

In [3]:
a=[1,2,3]
b=[[11,12],[21,22],[31,32]]

In [4]:
a=np.array(a)
b=np.array(b)

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([[11, 12],
       [21, 22],
       [31, 32]])

In [7]:
c=np.array([1,2])
c

array([1, 2])

In [8]:
np.dot(a,b)

array([146, 152])

In [9]:
np.outer(c,a)

array([[1, 2, 3],
       [2, 4, 6]])

In [10]:
np.outer(a,c)

array([[1, 2],
       [2, 4],
       [3, 6]])

In [11]:
np.dot(c,b.T)

array([35, 65, 95])