In [11]:
import numpy as np

In [19]:
a=np.array([1,2,3])
b=np.array([[10,100],[20,200],[30,300]])
b

array([[ 10, 100],
       [ 20, 200],
       [ 30, 300]])

In [16]:
c=np.dot(a,b)
c

array([ 140, 1400])

In [20]:
d=np.outer(c,a)
d

array([[ 140,  280,  420],
       [1400, 2800, 4200]])

In [22]:
e=np.dot(c,b.T)
e

array([141400, 282800, 424200])

In [23]:
[1,2,3]*0

[]